steps:
# build an image named gcr.io/designing-ml-systems/train:latest on cloudbuild machines
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/call-summarizatiion/summarization2023/summarization:v2', '.']

  #push the image to the container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/call-summarizatiion/summarization2023/summarization:v2']

images:
  - us-central1-docker.pkg.dev/call-summarizatiion/summarization2023/summarization:v2



