steps:
# build an image named gcr.io/designing-ml-systems/train:latest on cloudbuild machines
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'summarization:v2', '.']

#push the image to the container registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'summarization:v2']